### ISSUE TITLE
missing dependancies (archlinux)

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skyflash#45]
Os: Archlinux
skyflash version: v0.0.4-beta1-Linux

Initially I tried to build it from scratch but it was missing QtQuick modules as runtime dependancies for the gui when I tried to execute the binary produced by `make linux-static`

After downloading the release, the gui successfully launched, however when I selected to download the skybian image I got the error: `module 'ssl' has no attribute 'PROTOCOL_TLS'`

I believe the missing dependancy is available but am unable to install it at the moment due to conflicts.

I tried manually downloading the skybian image and selecting it but nothing happened.

**Comment by stdevPavelmc** [comment]
Please be sure **your are cloning the develop branch** and not the master one.

The master branch is used to stable releases (none yet, working hard to make it), the betas are held in develop, in fact at this moment there are new code in develop beyond the beta1, due to the work in progress for bug fixes and a few more commits are on his way tonight...

As mentioned in the README.md the default env for developers is Ubuntu 18.04 LTS, dependencies are handled by a target in the Makefile  (see `make deps`, or just `make` to get help)

You can take a peek and check the dependencies in the makefile to adjust it to your particular distro (archlinux in this case)

Nevertheless I will try to install archlinux and give it a try.

Cheers.
